/-
  Generated by lsc from a1.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «a1.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

def LETTERS : Array String := #["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

method rcColname (c : Int) return (res : String)
  ensures res.length ≥ 1
  ensures res.length ≤ 2
  do
    let mut col : Int := c
    if col > 702 then
      col := 702
    if col < 1 then
      col := 1
    let collow := Int.tmod (col - 1) 26
    let colhigh := (col - 1) / 26
    if colhigh > 0 then
      return LETTERS[(colhigh - 1).toNat]! ++ LETTERS[collow.toNat]!
    return LETTERS[collow.toNat]!

method crToCoord (c : Int) (r : Int) return (res : String)
  ensures res.length ≥ 2
  do
    let mut col : Int := c
    let mut row : Int := r
    if col < 1 then
      col := 1
    if col > 702 then
      col := 702
    if row < 1 then
      row := 1
    let collow := Int.tmod (col - 1) 26
    let colhigh := (col - 1) / 26
    if colhigh > 0 then
      return LETTERS[(colhigh - 1).toNat]! ++ LETTERS[collow.toNat]! ++ toString row
    return LETTERS[collow.toNat]! ++ toString row

method clampCol (c : Int) return (res : Int)
  ensures res ≥ 1
  ensures res ≤ 702
  do
    return Pure.clampCol c

method clampRow (r : Int) return (res : Int)
  ensures res ≥ 1
  do
    return Pure.clampRow r

method isColInBounds (c : Int) return (res : Bool)
  ensures res = true ∨ res = false
  do
    return Pure.isColInBounds c

method isRowInBounds (r : Int) return (res : Bool)
  ensures res = true ∨ res = false
  do
    return Pure.isRowInBounds r

method offsetCol (col : Int) (coloffset : Int) return (res : Int)
  ensures res = -1 ∨ res ≥ 1 ∧ res ≤ 702
  do
    return Pure.offsetCol col coloffset

method offsetRow (row : Int) (rowoffset : Int) return (res : Int)
  ensures res = -1 ∨ res ≥ 1
  do
    return Pure.offsetRow row rowoffset

method applyAxisOffset (value : Int) (offset : Int) (abs : Bool) (isCol : Bool) return (res : Int)
  ensures abs = true → res = value
  ensures res = -1 ∨ isCol = true ∧ res ≥ 1 ∧ res ≤ 702 ∨ isCol = false ∧ res ≥ 1 ∨ abs = true
  do
    return Pure.applyAxisOffset value offset abs isCol

method composeOffsets (a : Int) (b : Int) return (res : Int)
  ensures res = a + b
  do
    return Pure.composeOffsets a b

method offsetRelativeA1 (col : Int) (row : Int) (coloffset : Int) (rowoffset : Int) return (res : String)
  ensures res.length ≥ 2
  do
    let _t0 ← offsetCol col coloffset
    let c := _t0
    let _t1 ← offsetRow row rowoffset
    let r := _t1
    if c = -1 || r = -1 then
      return "#REF!"
    let _t2 ← crToCoord c r
    return _t2
