/-
  Generated by lsc from a1.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «a1.spec»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

def LETTERS : Array String := #["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

method rcColname (c : Int) return (res : String)
  ensures res.length ≥ 1
  ensures res.length ≤ 2
  do
    let mut col : Int := c
    if col > 702 then
      col := 702
    if col < 1 then
      col := 1
    let collow := Int.tmod (col - 1) 26
    let colhigh := (col - 1) / 26
    if colhigh > 0 then
      return LETTERS[(colhigh - 1).toNat]! ++ LETTERS[collow.toNat]!
    return LETTERS[collow.toNat]!

method crToCoord (c : Int) (r : Int) return (res : String)
  ensures res.length ≥ 2
  do
    let mut col : Int := c
    let mut row : Int := r
    if col < 1 then
      col := 1
    if col > 702 then
      col := 702
    if row < 1 then
      row := 1
    let collow := Int.tmod (col - 1) 26
    let colhigh := (col - 1) / 26
    if colhigh > 0 then
      return LETTERS[(colhigh - 1).toNat]! ++ LETTERS[collow.toNat]! ++ toString row
    return LETTERS[collow.toNat]! ++ toString row

method clampCol (c : Int) return (res : Int)
  ensures res ≥ 1
  ensures res ≤ 702
  ensures c ≥ 1 → c ≤ 702 → res = c
  do
    return Pure.clampCol c

method clampRow (r : Int) return (res : Int)
  ensures res ≥ 1
  ensures r ≥ 1 → res = r
  do
    return Pure.clampRow r

method isColInBounds (c : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ c ≥ 1 ∧ c ≤ 702
  do
    return Pure.isColInBounds c

method isRowInBounds (r : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ r ≥ 1
  do
    return Pure.isRowInBounds r

method offsetCol (col : Int) (coloffset : Int) return (res : Int)
  ensures res = -1 ∨ res ≥ 1 ∧ res ≤ 702
  ensures res ≠ -1 → res = col + coloffset
  ensures coloffset = 0 → col ≥ 1 → col ≤ 702 → res = col
  ensures col + coloffset < 1 ∨ col + coloffset > 702 → res = -1
  do
    return Pure.offsetCol col coloffset

method offsetRow (row : Int) (rowoffset : Int) return (res : Int)
  ensures res = -1 ∨ res ≥ 1
  ensures res ≠ -1 → res = row + rowoffset
  ensures rowoffset = 0 → row ≥ 1 → res = row
  ensures row + rowoffset < 1 → res = -1
  do
    return Pure.offsetRow row rowoffset

method applyAxisOffset (value : Int) (offset : Int) (abs : Bool) (isCol : Bool) return (res : Int)
  ensures abs = true → res = value
  ensures abs = false → isCol = true → res = Pure.offsetCol value offset
  ensures abs = false → isCol = false → res = Pure.offsetRow value offset
  do
    return Pure.applyAxisOffset value offset abs isCol

method composeOffsets (a : Int) (b : Int) return (res : Int)
  ensures res = a + b
  do
    return Pure.composeOffsets a b

method wouldOffsetRef (col : Int) (row : Int) (coloffset : Int) (rowoffset : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ Pure.offsetCol col coloffset = -1 ∨ Pure.offsetRow row rowoffset = -1
  do
    return Pure.wouldOffsetRef col row coloffset rowoffset

method offsetRelativeA1 (col : Int) (row : Int) (coloffset : Int) (rowoffset : Int) return (res : String)
  ensures res.length ≥ 2
  ensures Pure.wouldOffsetRef col row coloffset rowoffset = true → res = "#REF!"
  do
    let _t0 ← offsetCol col coloffset
    let c := _t0
    let _t1 ← offsetRow row rowoffset
    let r := _t1
    if c = -1 || r = -1 then
      return "#REF!"
    let _t2 ← crToCoord c r
    return _t2

method offsetA1Parts (col : Int) (row : Int) (absCol : Bool) (absRow : Bool) (coloffset : Int) (rowoffset : Int) return (res : OffsetA1PartsResult)
  ensures absCol = true → res.col = col ∨ res.col = -1 ∨ res.row = -1
  ensures absRow = true → res.row = row ∨ res.col = -1 ∨ res.row = -1
  ensures res.col = -1 ↔ res.row = -1
  do
    return Pure.offsetA1Parts col row absCol absRow coloffset rowoffset

method wouldOffsetA1Ref (col : Int) (row : Int) (absCol : Bool) (absRow : Bool) (coloffset : Int) (rowoffset : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ (Pure.offsetA1Parts col row absCol absRow coloffset rowoffset).col = -1
  do
    return Pure.wouldOffsetA1Ref col row absCol absRow coloffset rowoffset

method formatA1Parts (col : Int) (row : Int) (absCol : Bool) (absRow : Bool) return (res : String)
  ensures res.length ≥ 2
  ensures Pure.isColInBounds col = false ∨ Pure.isRowInBounds row = false → res = "#REF!"
  do
    let _t3 ← isColInBounds col
    let _t4 ← isRowInBounds row
    if !(_t3) || !(_t4) then
      return "#REF!"
    let mut s : String := ""
    if absCol then
      s := s ++ "$"
    let _t5 ← rcColname col
    s := s ++ _t5
    if absRow then
      s := s ++ "$"
    s := s ++ toString row
    return s

method offsetA1 (col : Int) (row : Int) (absCol : Bool) (absRow : Bool) (coloffset : Int) (rowoffset : Int) return (res : String)
  ensures res.length ≥ 2
  do
    let _t6 ← offsetA1Parts col row absCol absRow coloffset rowoffset
    let p := _t6
    if p.col = -1 || p.row = -1 then
      return "#REF!"
    let _t7 ← formatA1Parts p.col p.row absCol absRow
    return _t7

method adjustAxis (value : Int) (start : Int) (delta : Int) (isCol : Bool) return (res : Int)
  ensures res = -1 ∨ isCol = true ∧ res ≥ 1 ∧ res ≤ 702 ∨ isCol = false ∧ res ≥ 1
  ensures delta = 0 → res = value ∨ res = -1
  ensures delta < 0 → value ≥ start → value < start - delta → res = -1
  ensures value < start → isCol = true → value ≥ 1 → value ≤ 702 → res = value
  ensures value < start → isCol = false → value ≥ 1 → res = value
  do
    return Pure.adjustAxis value start delta isCol

method wouldAdjustRef (col : Int) (row : Int) (startCol : Int) (coloffset : Int) (startRow : Int) (rowoffset : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ Pure.adjustAxis col startCol coloffset true = -1 ∨ Pure.adjustAxis row startRow rowoffset false = -1
  do
    return Pure.wouldAdjustRef col row startCol coloffset startRow rowoffset

method adjustA1 (col : Int) (row : Int) (absCol : Bool) (absRow : Bool) (startCol : Int) (coloffset : Int) (startRow : Int) (rowoffset : Int) return (res : String)
  ensures res.length ≥ 2
  ensures Pure.wouldAdjustRef col row startCol coloffset startRow rowoffset = true → res = "#REF!"
  do
    let _t8 ← adjustAxis col startCol coloffset true
    let c := _t8
    let _t9 ← adjustAxis row startRow rowoffset false
    let r := _t9
    if c = -1 || r = -1 then
      return "#REF!"
    let _t10 ← formatA1Parts c r absCol absRow
    return _t10

method colFromRcRanks (colhigh : Int) (collow : Int) return (res : Int)
  ensures res = -1 ∨ res ≥ 1 ∧ res ≤ 702
  ensures collow ≥ 0 → collow ≤ 25 → colhigh = 0 → res = collow + 1
  ensures collow ≥ 0 → collow ≤ 25 → colhigh ≥ 1 → colhigh ≤ 26 → res = colhigh * 26 + collow + 1
  ensures collow < 0 ∨ collow > 25 ∨ colhigh < 0 ∨ colhigh > 26 → res = -1
  do
    return Pure.colFromRcRanks colhigh collow

method colToRcRanks (c : Int) return (res : ColToRcRanksResult)
  ensures res.collow ≥ 0
  ensures res.collow ≤ 25
  ensures res.colhigh ≥ 0
  ensures res.colhigh ≤ 26
  do
    return Pure.colToRcRanks c
