/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

structure OffsetA1PartsResult where
  col : Int
  row : Int
deriving Repr, Inhabited, DecidableEq

structure ColToRcRanksResult where
  colhigh : Int
  collow : Int
deriving Repr, Inhabited, DecidableEq

structure OffsetRectangleResult where
  ok : Bool
  col1 : Int
  row1 : Int
  col2 : Int
  row2 : Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def clampCol (c : Int) : Int :=
  if c < 1 then
    1
  else
    if c > 702 then
      702
    else
      c

def clampRow (r : Int) : Int :=
  if r < 1 then
    1
  else
    r

def isColInBounds (c : Int) : Bool :=
  c ≥ 1 ∧ c ≤ 702

def isRowInBounds (r : Int) : Bool :=
  r ≥ 1

def offsetCol (col : Int) (coloffset : Int) : Int :=
  let c := col + coloffset
  if c < 1 ∨ c > 702 then
    -1
  else
    c

def offsetRow (row : Int) (rowoffset : Int) : Int :=
  let r := row + rowoffset
  if r < 1 then
    -1
  else
    r

def applyAxisOffset (value : Int) (offset : Int) (abs : Bool) (isCol : Bool) : Int :=
  if abs then
    value
  else
    if isCol then
      offsetCol value offset
    else
      offsetRow value offset

def composeOffsets (a : Int) (b : Int) : Int :=
  a + b

def wouldOffsetRef (col : Int) (row : Int) (coloffset : Int) (rowoffset : Int) : Bool :=
  let c := offsetCol col coloffset
  let r := offsetRow row rowoffset
  c = -1 ∨ r = -1

def offsetA1Parts (col : Int) (row : Int) (absCol : Bool) (absRow : Bool) (coloffset : Int) (rowoffset : Int) : OffsetA1PartsResult :=
  let c := applyAxisOffset col coloffset absCol true
  let r := applyAxisOffset row rowoffset absRow false
  if c = -1 ∨ r = -1 then
    { col := -1, row := -1 }
  else
    if ¬(isColInBounds c) ∨ ¬(isRowInBounds r) then
      { col := -1, row := -1 }
    else
      { col := c, row := r }

def wouldOffsetA1Ref (col : Int) (row : Int) (absCol : Bool) (absRow : Bool) (coloffset : Int) (rowoffset : Int) : Bool :=
  let p := offsetA1Parts col row absCol absRow coloffset rowoffset
  p.col = -1

def adjustAxis (value : Int) (start : Int) (delta : Int) (isCol : Bool) : Int :=
  if delta < 0 ∧ value ≥ start ∧ value < start - delta then
    -1
  else
    let shifted := if value ≥ start then value + delta else value
    if isCol then
      if shifted < 1 ∨ shifted > 702 then
        -1
      else
        shifted
    else
      if shifted < 1 then
        -1
      else
        shifted

def wouldAdjustRef (col : Int) (row : Int) (startCol : Int) (coloffset : Int) (startRow : Int) (rowoffset : Int) : Bool :=
  let c := adjustAxis col startCol coloffset true
  let r := adjustAxis row startRow rowoffset false
  c = -1 ∨ r = -1

def colFromRcRanks (colhigh : Int) (collow : Int) : Int :=
  if collow < 0 ∨ collow > 25 then
    -1
  else
    if colhigh < 0 ∨ colhigh > 26 then
      -1
    else
      if colhigh = 0 then
        collow + 1
      else
        colhigh * 26 + collow + 1

def colToRcRanks (c : Int) : ColToRcRanksResult :=
  let col := clampCol c
  let collow := Int.tmod (col - 1) 26
  let colhigh := (col - 1) / 26
  { colhigh := colhigh, collow := collow }

def offsetRectangle (anchorCol : Int) (anchorRow : Int) (refRows : Int) (refCols : Int) (rowoffset : Int) (coloffset : Int) (height : Int) (width : Int) : OffsetRectangleResult :=
  let h := if height = 0 then refRows else height
  let w := if width = 0 then refCols else width
  let col1 := anchorCol + coloffset
  let row1 := anchorRow + rowoffset
  if h < 1 ∨ w < 1 ∨ col1 < 1 ∨ row1 < 1 ∨ col1 > MAX_COL ∨ row1 > MAX_ROW then
    { ok := false, col1 := 0, row1 := 0, col2 := 0, row2 := 0 }
  else
    let col2 := col1 + w - 1
    let row2 := row1 + h - 1
    if col2 > MAX_COL ∨ row2 > MAX_ROW then
      { ok := false, col1 := 0, row1 := 0, col2 := 0, row2 := 0 }
    else
      { ok := true, col1 := col1, row1 := row1, col2 := col2, row2 := row2 }

def wouldOffsetRectangleRef (anchorCol : Int) (anchorRow : Int) (refRows : Int) (refCols : Int) (rowoffset : Int) (coloffset : Int) (height : Int) (width : Int) : Bool :=
  let plan := offsetRectangle anchorCol anchorRow refRows refCols rowoffset coloffset height width
  plan.ok = false

def isAddressRowInBounds (row : Int) : Bool :=
  row ≥ 1 ∧ row ≤ MAX_ROW

def isAddressColInBounds (col : Int) : Bool :=
  col ≥ 1 ∧ col ≤ MAX_COL

def addressAbsRow (absNum : Int) : Bool :=
  absNum = 1 ∨ absNum = 2

def addressAbsCol (absNum : Int) : Bool :=
  absNum = 1 ∨ absNum = 3

def isValidAddressAbsNum (absNum : Int) : Bool :=
  absNum ≥ 1 ∧ absNum ≤ 4

def formatAddressR1C1 (row : Int) (col : Int) (absNum : Int) : String :=
  let absRow := addressAbsRow absNum
  let absCol := addressAbsCol absNum
  "R" ++ (if absRow then "" ++ toString row else "[" ++ toString row ++ "]") ++ "C" ++ (if absCol then "" ++ toString col else "[" ++ toString col ++ "]")

end Pure
