/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

structure OffsetA1PartsResult where
  col : Int
  row : Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def clampCol (c : Int) : Int :=
  if c < 1 then
    1
  else
    if c > 702 then
      702
    else
      c

def clampRow (r : Int) : Int :=
  if r < 1 then
    1
  else
    r

def isColInBounds (c : Int) : Bool :=
  c ≥ 1 ∧ c ≤ 702

def isRowInBounds (r : Int) : Bool :=
  r ≥ 1

def offsetCol (col : Int) (coloffset : Int) : Int :=
  let c := col + coloffset
  if c < 1 ∨ c > 702 then
    -1
  else
    c

def offsetRow (row : Int) (rowoffset : Int) : Int :=
  let r := row + rowoffset
  if r < 1 then
    -1
  else
    r

def applyAxisOffset (value : Int) (offset : Int) (abs : Bool) (isCol : Bool) : Int :=
  if abs then
    value
  else
    if isCol then
      offsetCol value offset
    else
      offsetRow value offset

def composeOffsets (a : Int) (b : Int) : Int :=
  a + b

def wouldOffsetRef (col : Int) (row : Int) (coloffset : Int) (rowoffset : Int) : Bool :=
  let c := offsetCol col coloffset
  let r := offsetRow row rowoffset
  c = -1 ∨ r = -1

def offsetA1Parts (col : Int) (row : Int) (absCol : Bool) (absRow : Bool) (coloffset : Int) (rowoffset : Int) : OffsetA1PartsResult :=
  let c := applyAxisOffset col coloffset absCol true
  let r := applyAxisOffset row rowoffset absRow false
  if c = -1 ∨ r = -1 then
    { col := -1, row := -1 }
  else
    if ¬(isColInBounds c) ∨ ¬(isRowInBounds r) then
      { col := -1, row := -1 }
    else
      { col := c, row := r }

def adjustAxis (value : Int) (start : Int) (delta : Int) (isCol : Bool) : Int :=
  if delta < 0 ∧ value ≥ start ∧ value < start - delta then
    -1
  else
    let shifted := if value ≥ start then value + delta else value
    if isCol then
      if shifted < 1 ∨ shifted > 702 then
        -1
      else
        shifted
    else
      if shifted < 1 then
        -1
      else
        shifted

end Pure
