/-
  Generated by lsc from branch.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «branch.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method switchBranch (hitIndex : Int) (caseCount : Int) (hasDefault : Bool) return (res : Int)
  ensures hitIndex ≥ 0 → res = hitIndex
  ensures hitIndex < 0 → hasDefault = true → res = caseCount
  ensures hitIndex < 0 → hasDefault = false → res = -1
  do
    return Pure.switchBranch hitIndex caseCount hasDefault

method keepJoinItem (ignoreEmpty : Bool) (isEmptyText : Bool) return (res : Bool)
  ensures res = (ignoreEmpty = false ∨ isEmptyText = false)
  do
    return Pure.keepJoinItem ignoreEmpty isEmptyText

method emitDelimiterBefore (keptSoFar : Int) return (res : Bool)
  ensures keptSoFar > 0 → res = true
  ensures keptSoFar ≤ 0 → res = false
  do
    return Pure.emitDelimiterBefore keptSoFar
