/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def switchBranch (hitIndex : Int) (caseCount : Int) (hasDefault : Bool) : Int :=
  if hitIndex ≥ 0 then
    hitIndex
  else
    if hasDefault then
      caseCount
    else
      -1

def keepJoinItem (ignoreEmpty : Bool) (isEmptyText : Bool) : Bool :=
  if ignoreEmpty = false then
    true
  else
    isEmptyText = false

def emitDelimiterBefore (keptSoFar : Int) : Bool :=
  keptSoFar > 0

end Pure
