/-
  Generated by lsc from chart.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «chart.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isValidChartType (chartType : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ chartType = 0 ∨ chartType = 1 ∨ chartType = 2 ∨ chartType = 3 ∨ chartType = 4 ∨ chartType = 5
  do
    return Pure.isValidChartType chartType

method isValidSourceShape (rows : Int) (cols : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ rows > 0 ∧ cols > 0
  do
    return Pure.isValidSourceShape rows cols

method seriesCount (rows : Int) (cols : Int) (seriesInRows : Bool) return (res : Int)
  ensures seriesInRows = true → res = rows
  ensures seriesInRows = false → res = cols
  do
    return Pure.seriesCount rows cols seriesInRows

method categoryCount (rows : Int) (cols : Int) (seriesInRows : Bool) return (res : Int)
  ensures seriesInRows = true → res = cols
  ensures seriesInRows = false → res = rows
  do
    return Pure.categoryCount rows cols seriesInRows

method minSeriesForType (chartType : Int) return (res : Int)
  ensures chartType = 5 → res = 2
  ensures chartType ≠ 5 → res = 1
  do
    return Pure.minSeriesForType chartType

method isSourceValidForType (chartType : Int) (rows : Int) (cols : Int) (seriesInRows : Bool) return (res : Bool)
  ensures Pure.isValidChartType chartType = false → res = false
  ensures Pure.isValidChartType chartType = true → Pure.isValidSourceShape rows cols = false → res = false
  ensures Pure.isValidChartType chartType = true → Pure.isValidSourceShape rows cols = true → Pure.seriesCount rows cols seriesInRows < Pure.minSeriesForType chartType → res = false
  ensures res = true ↔ Pure.isValidChartType chartType = true ∧ Pure.isValidSourceShape rows cols = true ∧ Pure.seriesCount rows cols seriesInRows ≥ Pure.minSeriesForType chartType
  do
    return Pure.isSourceValidForType chartType rows cols seriesInRows

method domainMin (hasPrior : Bool) (priorMin : Int) (value : Int) return (res : Int)
  ensures hasPrior = false → res = value
  ensures hasPrior = true → value < priorMin → res = value
  ensures hasPrior = true → value ≥ priorMin → res = priorMin
  do
    return Pure.domainMin hasPrior priorMin value

method domainMax (hasPrior : Bool) (priorMax : Int) (value : Int) return (res : Int)
  ensures hasPrior = false → res = value
  ensures hasPrior = true → value > priorMax → res = value
  ensures hasPrior = true → value ≤ priorMax → res = priorMax
  do
    return Pure.domainMax hasPrior priorMax value

method shouldIncludeZeroBaseline (chartType : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ chartType = 0 ∨ chartType = 1 ∨ chartType = 3
  do
    return Pure.shouldIncludeZeroBaseline chartType

method baselineMin (includeZero : Bool) (min : Int) return (res : Int)
  ensures includeZero = false → res = min
  ensures includeZero = true → min > 0 → res = 0
  ensures includeZero = true → min ≤ 0 → res = min
  do
    return Pure.baselineMin includeZero min

method baselineMax (includeZero : Bool) (max : Int) return (res : Int)
  ensures includeZero = false → res = max
  ensures includeZero = true → max < 0 → res = 0
  ensures includeZero = true → max ≥ 0 → res = max
  do
    return Pure.baselineMax includeZero max

method isDegenerateDomain (min : Int) (max : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ min = max
  do
    return Pure.isDegenerateDomain min max

method isWithinSheetBounds (anchorCol : Int) (anchorRow : Int) (maxCol : Int) (maxRow : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ anchorCol ≥ 1 ∧ anchorCol ≤ maxCol ∧ anchorRow ≥ 1 ∧ anchorRow ≤ maxRow
  do
    return Pure.isWithinSheetBounds anchorCol anchorRow maxCol maxRow

method isValidDimension (px : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ px ≥ 40 ∧ px ≤ 4000
  do
    return Pure.isValidDimension px

method clampDimension (px : Int) return (res : Int)
  ensures res ≥ 40
  ensures res ≤ 4000
  ensures px < 40 → res = 40
  ensures px > 4000 → res = 4000
  ensures px ≥ 40 → px ≤ 4000 → res = px
  do
    return Pure.clampDimension px

method planPlacementStatus (anchorCol : Int) (anchorRow : Int) (widthPx : Int) (heightPx : Int) (maxCol : Int) (maxRow : Int) return (res : Int)
  ensures Pure.isWithinSheetBounds anchorCol anchorRow maxCol maxRow = false → res = 1
  ensures Pure.isWithinSheetBounds anchorCol anchorRow maxCol maxRow = true → Pure.isValidDimension widthPx = false ∨ Pure.isValidDimension heightPx = false → res = 2
  ensures res = 0 ↔ Pure.isWithinSheetBounds anchorCol anchorRow maxCol maxRow = true ∧ Pure.isValidDimension widthPx = true ∧ Pure.isValidDimension heightPx = true
  do
    return Pure.planPlacementStatus anchorCol anchorRow widthPx heightPx maxCol maxRow
