/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def isValidChartType (chartType : Int) : Bool :=
  chartType = 0 ∨ chartType = 1 ∨ chartType = 2 ∨ chartType = 3 ∨ chartType = 4 ∨ chartType = 5

def isValidSourceShape (rows : Int) (cols : Int) : Bool :=
  rows > 0 ∧ cols > 0

def seriesCount (rows : Int) (cols : Int) (seriesInRows : Bool) : Int :=
  if seriesInRows then
    rows
  else
    cols

def categoryCount (rows : Int) (cols : Int) (seriesInRows : Bool) : Int :=
  if seriesInRows then
    cols
  else
    rows

def minSeriesForType (chartType : Int) : Int :=
  if chartType = 5 then
    2
  else
    1

def isSourceValidForType (chartType : Int) (rows : Int) (cols : Int) (seriesInRows : Bool) : Bool :=
  if ¬(isValidChartType chartType) then
    false
  else
    if ¬(isValidSourceShape rows cols) then
      false
    else
      seriesCount rows cols seriesInRows ≥ minSeriesForType chartType

def domainMin (hasPrior : Bool) (priorMin : Int) (value : Int) : Int :=
  if ¬(hasPrior) then
    value
  else
    if value < priorMin then
      value
    else
      priorMin

def domainMax (hasPrior : Bool) (priorMax : Int) (value : Int) : Int :=
  if ¬(hasPrior) then
    value
  else
    if value > priorMax then
      value
    else
      priorMax

def shouldIncludeZeroBaseline (chartType : Int) : Bool :=
  chartType = 0 ∨ chartType = 1 ∨ chartType = 3

def baselineMin (includeZero : Bool) (min : Int) : Int :=
  if ¬(includeZero) then
    min
  else
    if min > 0 then
      0
    else
      min

def baselineMax (includeZero : Bool) (max : Int) : Int :=
  if ¬(includeZero) then
    max
  else
    if max < 0 then
      0
    else
      max

def isDegenerateDomain (min : Int) (max : Int) : Bool :=
  min = max

def isWithinSheetBounds (anchorCol : Int) (anchorRow : Int) (maxCol : Int) (maxRow : Int) : Bool :=
  anchorCol ≥ 1 ∧ anchorCol ≤ maxCol ∧ anchorRow ≥ 1 ∧ anchorRow ≤ maxRow

def isValidDimension (px : Int) : Bool :=
  px ≥ 40 ∧ px ≤ 4000

def clampDimension (px : Int) : Int :=
  if px < 40 then
    40
  else
    if px > 4000 then
      4000
    else
      px

def planPlacementStatus (anchorCol : Int) (anchorRow : Int) (widthPx : Int) (heightPx : Int) (maxCol : Int) (maxRow : Int) : Int :=
  if ¬(isWithinSheetBounds anchorCol anchorRow maxCol maxRow) then
    1
  else
    if ¬(isValidDimension widthPx) ∨ ¬(isValidDimension heightPx) then
      2
    else
      0

end Pure
