/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

structure FieldMerge where
  defined : Bool
  value : Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def isValidOp (op : Int) : Bool :=
  op = 0 ∨ op = 1 ∨ op = 2 ∨ op = 3 ∨ op = 4 ∨ op = 5 ∨ op = 6

def matchesCellIs (op : Int) (cmp : Int) (geLow : Bool) (leHigh : Bool) : Bool :=
  if op = 0 then
    cmp > 0
  else
    if op = 1 then
      cmp ≥ 0
    else
      if op = 2 then
        cmp < 0
      else
        if op = 3 then
          cmp ≤ 0
        else
          if op = 4 then
            cmp = 0
          else
            if op = 5 then
              cmp ≠ 0
            else
              if op = 6 then
                geLow = true ∧ leHigh = true
              else
                false

def isDuplicateValue (count : Int) : Bool :=
  count > 1

def isUniqueValue (count : Int) : Bool :=
  count = 1

def shouldEvaluate (stoppedBefore : Bool) : Bool :=
  stoppedBefore = false

def nextStopped (stoppedBefore : Bool) (matched : Bool) (stopIfTrue : Bool) : Bool :=
  if stoppedBefore = true then
    true
  else
    matched = true ∧ stopIfTrue = true

def ruleApplies (stoppedBefore : Bool) (matched : Bool) : Bool :=
  stoppedBefore = false ∧ matched = true

def mergeStyleField (currentDefined : Bool) (currentValue : Int) (candidateApplies : Bool) (candidateDefined : Bool) (candidateValue : Int) : FieldMerge :=
  if currentDefined = true then
    { defined := true, value := currentValue }
  else
    if candidateApplies = true ∧ candidateDefined = true then
      { defined := true, value := candidateValue }
    else
      { defined := false, value := currentValue }

end Pure
