/-
  Generated by lsc from condfmt.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «condfmt.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isValidOp (op : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ op = 0 ∨ op = 1 ∨ op = 2 ∨ op = 3 ∨ op = 4 ∨ op = 5 ∨ op = 6
  do
    return Pure.isValidOp op

method matchesCellIs (op : Int) (cmp : Int) (geLow : Bool) (leHigh : Bool) return (res : Bool)
  ensures res = true ∨ res = false
  ensures op = 0 → (res = true ↔ cmp > 0)
  ensures op = 1 → (res = true ↔ cmp ≥ 0)
  ensures op = 2 → (res = true ↔ cmp < 0)
  ensures op = 3 → (res = true ↔ cmp ≤ 0)
  ensures op = 4 → (res = true ↔ cmp = 0)
  ensures op = 5 → (res = true ↔ cmp ≠ 0)
  ensures op = 6 → (res = true ↔ geLow = true ∧ leHigh = true)
  ensures op ≠ 0 → op ≠ 1 → op ≠ 2 → op ≠ 3 → op ≠ 4 → op ≠ 5 → op ≠ 6 → res = false
  do
    return Pure.matchesCellIs op cmp geLow leHigh

method isDuplicateValue (count : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ count > 1
  do
    return Pure.isDuplicateValue count

method isUniqueValue (count : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ count = 1
  do
    return Pure.isUniqueValue count

method shouldEvaluate (stoppedBefore : Bool) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ stoppedBefore = false
  do
    return Pure.shouldEvaluate stoppedBefore

method nextStopped (stoppedBefore : Bool) (matched : Bool) (stopIfTrue : Bool) return (res : Bool)
  ensures res = true ∨ res = false
  ensures stoppedBefore = true → res = true
  ensures stoppedBefore = false → (res = true ↔ matched = true ∧ stopIfTrue = true)
  do
    return Pure.nextStopped stoppedBefore matched stopIfTrue

method ruleApplies (stoppedBefore : Bool) (matched : Bool) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ stoppedBefore = false ∧ matched = true
  do
    return Pure.ruleApplies stoppedBefore matched

method mergeStyleField (currentDefined : Bool) (currentValue : Int) (candidateApplies : Bool) (candidateDefined : Bool) (candidateValue : Int) return (res : FieldMerge)
  ensures currentDefined = true → res.defined = true ∧ res.value = currentValue
  ensures currentDefined = false → candidateApplies = true → candidateDefined = true → res.defined = true ∧ res.value = candidateValue
  ensures currentDefined = false → candidateApplies = false ∨ candidateDefined = false → res.defined = false
  do
    return Pure.mergeStyleField currentDefined currentValue candidateApplies candidateDefined candidateValue
