/-
  Generated by lsc from criteria.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «criteria.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method nextErrorState (hadError : Bool) (cellIsError : Bool) return (res : Bool)
  ensures res = (hadError = true ∨ cellIsError = true)
  do
    return Pure.nextErrorState hadError cellIsError

method nextMax (hasPrev : Bool) (prevMax : Int) (v : Int) return (res : Int)
  ensures hasPrev = false → res = v
  ensures hasPrev = true → v > prevMax → res = v
  ensures hasPrev = true → v ≤ prevMax → res = prevMax
  do
    return Pure.nextMax hasPrev prevMax v

method nextMin (hasPrev : Bool) (prevMin : Int) (v : Int) return (res : Int)
  ensures hasPrev = false → res = v
  ensures hasPrev = true → v < prevMin → res = v
  ensures hasPrev = true → v ≥ prevMin → res = prevMin
  do
    return Pure.nextMin hasPrev prevMin v

method shapesMatch (ncolsA : Int) (nrowsA : Int) (ncolsB : Int) (nrowsB : Int) return (res : Bool)
  ensures res = true ↔ ncolsA = ncolsB ∧ nrowsA = nrowsB
  do
    return Pure.shapesMatch ncolsA nrowsA ncolsB nrowsB

method resultDecision (fn : Int) (errorPresent : Bool) (numericCount : Int) return (res : Int)
  ensures fn = 0 → res = 0
  ensures fn ≠ 0 → errorPresent = true → res = 1
  ensures fn = 1 → errorPresent = false → numericCount > 0 → res = 2
  ensures fn = 1 → errorPresent = false → numericCount ≤ 0 → res = 3
  ensures fn = 2 → errorPresent = false → numericCount > 0 → res = 4
  ensures fn = 2 → errorPresent = false → numericCount ≤ 0 → res = 6
  ensures fn = 3 → errorPresent = false → numericCount > 0 → res = 5
  ensures fn = 3 → errorPresent = false → numericCount ≤ 0 → res = 6
  do
    return Pure.resultDecision fn errorPresent numericCount
