/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def nextErrorState (hadError : Bool) (cellIsError : Bool) : Bool :=
  if hadError = true then
    true
  else
    cellIsError

def nextMax (hasPrev : Bool) (prevMax : Int) (v : Int) : Int :=
  if hasPrev = false then
    v
  else
    if v > prevMax then
      v
    else
      prevMax

def nextMin (hasPrev : Bool) (prevMin : Int) (v : Int) : Int :=
  if hasPrev = false then
    v
  else
    if v < prevMin then
      v
    else
      prevMin

def shapesMatch (ncolsA : Int) (nrowsA : Int) (ncolsB : Int) (nrowsB : Int) : Bool :=
  ncolsA = ncolsB ∧ nrowsA = nrowsB

def resultDecision (fn : Int) (errorPresent : Bool) (numericCount : Int) : Int :=
  if fn = 0 then
    0
  else
    if errorPresent = true then
      1
    else
      if fn = 1 then
        if numericCount > 0 then
          2
        else
          3
      else
        if fn = 2 then
          if numericCount > 0 then
            4
          else
            6
        else
          if numericCount > 0 then
            5
          else
            6

end Pure
