/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def ClassifyPeriodDomain (nper : Int) (per : Int) (perIsInteger : Bool) : Int :=
  if nper ≤ 0 then
    PERIOD_NPER_INVALID
  else
    if per < 1 ∨ per > nper then
      PERIOD_OUT_OF_RANGE
    else
      if ¬(perIsInteger) then
        PERIOD_NOT_INTEGER
      else
        PERIOD_OK

def ClassifySignRequirement (hasPositive : Bool) (hasNegative : Bool) : Int :=
  if hasPositive ∧ hasNegative then
    SIGN_OK
  else
    if ¬(hasPositive) ∧ ¬(hasNegative) then
      SIGN_MISSING_BOTH
    else
      if ¬(hasPositive) then
        SIGN_MISSING_POSITIVE
      else
        SIGN_MISSING_NEGATIVE

def ClassifyDateAgainstAnchor (anchor : Int) (date : Int) : Int :=
  if date < anchor then
    DATE_BEFORE_ANCHOR
  else
    DATE_OK

end Pure
