/-
  Generated by lsc from finance-policy.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «finance-policy.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

def PERIOD_OK : Int := 0

def PERIOD_NPER_INVALID : Int := 1

def PERIOD_OUT_OF_RANGE : Int := 2

def PERIOD_NOT_INTEGER : Int := 3

def SIGN_OK : Int := 0

def SIGN_MISSING_POSITIVE : Int := 1

def SIGN_MISSING_NEGATIVE : Int := 2

def SIGN_MISSING_BOTH : Int := 3

def DATE_OK : Int := 0

def DATE_BEFORE_ANCHOR : Int := 1

method ClassifyPeriodDomain (nper : Int) (per : Int) (perIsInteger : Bool) return (res : Int)
  ensures nper ≤ 0 → res = 1
  ensures nper > 0 → per < 1 ∨ per > nper → res = 2
  ensures nper > 0 → per ≥ 1 → per ≤ nper → perIsInteger = false → res = 3
  ensures nper > 0 → per ≥ 1 → per ≤ nper → perIsInteger = true → res = 0
  do
    return Pure.ClassifyPeriodDomain nper per perIsInteger

method ClassifySignRequirement (hasPositive : Bool) (hasNegative : Bool) return (res : Int)
  ensures hasPositive = true → hasNegative = true → res = 0
  ensures hasPositive = false → hasNegative = true → res = 1
  ensures hasPositive = true → hasNegative = false → res = 2
  ensures hasPositive = false → hasNegative = false → res = 3
  do
    return Pure.ClassifySignRequirement hasPositive hasNegative

method ClassifyDateAgainstAnchor (anchor : Int) (date : Int) return (res : Int)
  ensures date < anchor → res = 1
  ensures date ≥ anchor → res = 0
  do
    return Pure.ClassifyDateAgainstAnchor anchor date
