/-
  Generated by lsc from html-table.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «html-table.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

def PLACEMENT_OPEN : Int := 0

def PLACEMENT_COLLISION : Int := 1

def TABLE_OK : Int := 0

def TABLE_INVALID_SPAN : Int := 1

def TABLE_BOUNDS_OVERFLOW : Int := 2

method isValidSpan (rowSpan : Int) (colSpan : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ rowSpan > 0 ∧ colSpan > 0
  do
    return Pure.isValidSpan rowSpan colSpan

method endCol (anchorCol : Int) (colSpan : Int) return (res : Int)
  ensures res = anchorCol + colSpan - 1
  do
    return Pure.endCol anchorCol colSpan

method endRow (anchorRow : Int) (rowSpan : Int) return (res : Int)
  ensures res = anchorRow + rowSpan - 1
  do
    return Pure.endRow anchorRow rowSpan

method inRect (col : Int) (row : Int) (anchorCol : Int) (anchorRow : Int) (rowSpan : Int) (colSpan : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ col ≥ anchorCol ∧ col ≤ Pure.endCol anchorCol colSpan ∧ row ≥ anchorRow ∧ row ≤ Pure.endRow anchorRow rowSpan
  do
    return Pure.inRect col row anchorCol anchorRow rowSpan colSpan

method rectCellCount (rowSpan : Int) (colSpan : Int) return (res : Int)
  ensures res = rowSpan * colSpan
  do
    return Pure.rectCellCount rowSpan colSpan

method classifySlot (isOccupied : Bool) return (res : Int)
  ensures res = 0 ∨ res = 1
  ensures isOccupied = true → res = 1
  ensures isOccupied = false → res = 0
  do
    return Pure.classifySlot isOccupied

method canPlaceRect (anyOccupied : Bool) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ anyOccupied = false
  do
    return Pure.canPlaceRect anyOccupied

method isWithinTableBounds (anchorCol : Int) (anchorRow : Int) (rowSpan : Int) (colSpan : Int) (maxCol : Int) (maxRow : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ anchorCol ≥ 1 ∧ anchorRow ≥ 1 ∧ Pure.endCol anchorCol colSpan ≤ maxCol ∧ Pure.endRow anchorRow rowSpan ≤ maxRow
  do
    return Pure.isWithinTableBounds anchorCol anchorRow rowSpan colSpan maxCol maxRow

method planTableStatus (anchorCol : Int) (anchorRow : Int) (rowSpan : Int) (colSpan : Int) (maxCol : Int) (maxRow : Int) return (res : Int)
  ensures Pure.isValidSpan rowSpan colSpan = false → res = 1
  ensures Pure.isValidSpan rowSpan colSpan = true → Pure.isWithinTableBounds anchorCol anchorRow rowSpan colSpan maxCol maxRow = false → res = 2
  ensures res = 0 ↔ Pure.isValidSpan rowSpan colSpan = true ∧ Pure.isWithinTableBounds anchorCol anchorRow rowSpan colSpan maxCol maxRow = true
  do
    return Pure.planTableStatus anchorCol anchorRow rowSpan colSpan maxCol maxRow
