/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def isValidSpan (rowSpan : Int) (colSpan : Int) : Bool :=
  rowSpan > 0 ∧ colSpan > 0

def endCol (anchorCol : Int) (colSpan : Int) : Int :=
  anchorCol + colSpan - 1

def endRow (anchorRow : Int) (rowSpan : Int) : Int :=
  anchorRow + rowSpan - 1

def inRect (col : Int) (row : Int) (anchorCol : Int) (anchorRow : Int) (rowSpan : Int) (colSpan : Int) : Bool :=
  col ≥ anchorCol ∧ col ≤ endCol anchorCol colSpan ∧ row ≥ anchorRow ∧ row ≤ endRow anchorRow rowSpan

def rectCellCount (rowSpan : Int) (colSpan : Int) : Int :=
  rowSpan * colSpan

def classifySlot (isOccupied : Bool) : Int :=
  if isOccupied then
    PLACEMENT_COLLISION
  else
    PLACEMENT_OPEN

def canPlaceRect (anyOccupied : Bool) : Bool :=
  ¬(anyOccupied)

def isWithinTableBounds (anchorCol : Int) (anchorRow : Int) (rowSpan : Int) (colSpan : Int) (maxCol : Int) (maxRow : Int) : Bool :=
  anchorCol ≥ 1 ∧ anchorRow ≥ 1 ∧ endCol anchorCol colSpan ≤ maxCol ∧ endRow anchorRow rowSpan ≤ maxRow

def planTableStatus (anchorCol : Int) (anchorRow : Int) (rowSpan : Int) (colSpan : Int) (maxCol : Int) (maxRow : Int) : Int :=
  if ¬(isValidSpan rowSpan colSpan) then
    TABLE_INVALID_SPAN
  else
    if ¬(isWithinTableBounds anchorCol anchorRow rowSpan colSpan maxCol maxRow) then
      TABLE_BOUNDS_OVERFLOW
    else
      TABLE_OK

end Pure
