/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def classifyArity (paramCount : Int) (argCount : Int) : Int :=
  if argCount < paramCount then
    1
  else
    if argCount > paramCount then
      2
    else
      0

def recursionStatus (depth : Int) (maxDepth : Int) : Int :=
  if depth > maxDepth then
    1
  else
    0

def shapesMatch (rows1 : Int) (cols1 : Int) (rows2 : Int) (cols2 : Int) : Bool :=
  rows1 = rows2 ∧ cols1 = cols2

def isValidRectShape (rows : Int) (cols : Int) : Bool :=
  rows > 0 ∧ cols > 0

end Pure
