/-
  Generated by lsc from lambda-scope.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «lambda-scope.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method classifyArity (paramCount : Int) (argCount : Int) return (res : Int)
  ensures argCount < paramCount → res = 1
  ensures argCount > paramCount → res = 2
  ensures argCount = paramCount → res = 0
  do
    return Pure.classifyArity paramCount argCount

method resolveScopeIndex (matches : Array Bool) return (res : Int)
  ensures matches.size = 0 → res = -1
  ensures res ≥ -1
  ensures res < matches.size
  ensures res ≥ 0 → matches[res.toNat]! = true
  ensures res ≥ 0 → ∀ j : Int, res < j → j < matches.size → matches[j.toNat]! = false
  ensures res = -1 → ∀ j : Int, 0 ≤ j → j < matches.size → matches[j.toNat]! = false
  do
    let mut i : Int := matches.size - 1
    let mut _loopRet : Int := -1
    while i ≥ 0
      invariant i ≥ -1
      invariant i < matches.size
      invariant ∀ k : Int, i < k → k < matches.size → matches[k.toNat]! = false
      invariant matches.size = 0 → _loopRet = -1
      invariant _loopRet ≥ -1
      invariant _loopRet < matches.size
      invariant _loopRet ≥ 0 → matches[_loopRet.toNat]! = true
      invariant _loopRet ≥ 0 → ∀ j : Int, _loopRet < j → j < matches.size → matches[j.toNat]! = false
      invariant _loopRet = -1 → ∀ j : Int, 0 ≤ j → j < matches.size → matches[j.toNat]! = false
      done_with True
      decreasing i
    do
      if matches[i.toNat]! then
        _loopRet := i
        break
      i := i - 1
    return _loopRet

method recursionStatus (depth : Int) (maxDepth : Int) return (res : Int)
  ensures depth > maxDepth → res = 1
  ensures depth ≤ maxDepth → res = 0
  do
    return Pure.recursionStatus depth maxDepth

method shapesMatch (rows1 : Int) (cols1 : Int) (rows2 : Int) (cols2 : Int) return (res : Bool)
  ensures res = true ↔ rows1 = rows2 ∧ cols1 = cols2
  do
    return Pure.shapesMatch rows1 cols1 rows2 cols2

method isValidRectShape (rows : Int) (cols : Int) return (res : Bool)
  ensures res = true ↔ rows > 0 ∧ cols > 0
  do
    return Pure.isValidRectShape rows cols
