/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def groupingCharFor (decimalChar : String) : String :=
  if decimalChar = "." then
    ","
  else
    if decimalChar = "," then
      "."
    else
      ""

def isAsciiDigit (ch : String) : Bool :=
  ch.length = 1 ∧ ch ≥ "0" ∧ ch ≤ "9"

def isNameChar (ch : String) : Bool :=
  ch.length = 1 ∧ (ch ≥ "A" ∧ ch ≤ "Z" ∨ ch ≥ "0" ∧ ch ≤ "9" ∨ ch = "_" ∨ ch = ".")

end Pure
