/-
  Generated by lsc from number-parse.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «number-parse.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method groupingCharFor (decimalChar : String) return (res : String)
  ensures res = "" ∨ res = "," ∨ res = "."
  ensures decimalChar = "." → res = ","
  ensures decimalChar = "," → res = "."
  ensures decimalChar ≠ "." → decimalChar ≠ "," → res = ""
  do
    return Pure.groupingCharFor decimalChar

method isAsciiDigit (ch : String) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ ch.length = 1 ∧ ch ≥ "0" ∧ ch ≤ "9"
  do
    return Pure.isAsciiDigit ch

method isNameChar (ch : String) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ ch.length = 1 ∧ (ch ≥ "A" ∧ ch ≤ "Z" ∨ ch ≥ "0" ∧ ch ≤ "9" ∨ ch = "_" ∨ ch = ".")
  do
    return Pure.isNameChar ch
