/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def typeRank (typeChar : String) : Int :=
  if typeChar = "n" then
    0
  else
    if typeChar = "t" then
      1
    else
      if typeChar = "e" then
        2
      else
        3

def compareGroupKey (rankA : Int) (rankB : Int) (sameTypeCompare : Int) (indexA : Int) (indexB : Int) : Int :=
  if rankA ≠ rankB then
    if rankA < rankB then
      -1
    else
      1
  else
    if sameTypeCompare ≠ 0 then
      sameTypeCompare
    else
      if indexA < indexB then
        -1
      else
        if indexA > indexB then
          1
        else
          0

def isNumericType (typeChar : String) : Bool :=
  typeChar = "n"

def isBlankType (typeChar : String) : Bool :=
  typeChar = "b"

def aggregateContributesNumeric (typeChar : String) : Bool :=
  isNumericType typeChar

def aggregateContributesCountA (typeChar : String) : Bool :=
  isBlankType typeChar = false

def aggregateContributes (aggFn : Int) (typeChar : String) : Bool :=
  if aggFn = 2 then
    aggregateContributesCountA typeChar
  else
    aggregateContributesNumeric typeChar

def nextSum (sum : Int) (contributes : Bool) (value : Int) : Int :=
  if contributes = true then
    sum + value
  else
    sum

def nextCount (count : Int) (contributes : Bool) : Int :=
  if contributes = true then
    count + 1
  else
    count

def nextMin (min : Int) (hasMin : Bool) (contributes : Bool) (value : Int) : Int :=
  if contributes = false then
    min
  else
    if hasMin = false then
      value
    else
      if value < min then
        value
      else
        min

def nextMax (max : Int) (hasMax : Bool) (contributes : Bool) (value : Int) : Int :=
  if contributes = false then
    max
  else
    if hasMax = false then
      value
    else
      if value > max then
        value
      else
        max

def aggregateStatus (aggFn : Int) (numericCount : Int) : Int :=
  if aggFn = 3 ∧ numericCount = 0 then
    1
  else
    0

def isValidPivotShape (rows : Int) (cols : Int) : Bool :=
  rows > 0 ∧ cols > 0

def pivotEndCol (anchorCol : Int) (cols : Int) : Int :=
  anchorCol + cols - 1

def pivotEndRow (anchorRow : Int) (rows : Int) : Int :=
  anchorRow + rows - 1

def isPivotWithinBounds (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) (maxCol : Int) (maxRow : Int) : Bool :=
  anchorCol ≥ 1 ∧ anchorRow ≥ 1 ∧ pivotEndCol anchorCol cols ≤ maxCol ∧ pivotEndRow anchorRow rows ≤ maxRow

def pivotCellCount (rows : Int) (cols : Int) : Int :=
  rows * cols

def isPivotWithinBudget (rows : Int) (cols : Int) (maxCells : Int) : Bool :=
  pivotCellCount rows cols ≤ maxCells

def planPivotStatus (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) (maxCol : Int) (maxRow : Int) (maxCells : Int) : Int :=
  if ¬(isValidPivotShape rows cols) then
    1
  else
    if ¬(isPivotWithinBounds anchorCol anchorRow rows cols maxCol maxRow) then
      2
    else
      if ¬(isPivotWithinBudget rows cols maxCells) then
        3
      else
        0

def classifyPivotClaim (isAnchorCell : Bool) (isBlank : Bool) (isOwnedBySamePivot : Bool) (isForeignOwned : Bool) (hasUserContent : Bool) (isMergedTarget : Bool) : Int :=
  if isAnchorCell = true then
    0
  else
    if isForeignOwned = true ∨ hasUserContent = true ∨ isMergedTarget = true then
      2
    else
      if isBlank = true ∨ isOwnedBySamePivot = true then
        1
      else
        2

end Pure
