/-
  Generated by lsc from pivot.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «pivot.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method typeRank (typeChar : String) return (res : Int)
  ensures typeChar = "n" → res = 0
  ensures typeChar = "t" → res = 1
  ensures typeChar = "e" → res = 2
  ensures typeChar ≠ "n" → typeChar ≠ "t" → typeChar ≠ "e" → res = 3
  do
    return Pure.typeRank typeChar

method compareGroupKey (rankA : Int) (rankB : Int) (sameTypeCompare : Int) (indexA : Int) (indexB : Int) return (res : Int)
  ensures rankA ≠ rankB → rankA < rankB → res = -1
  ensures rankA ≠ rankB → rankA > rankB → res = 1
  ensures rankA = rankB → sameTypeCompare ≠ 0 → res = sameTypeCompare
  ensures rankA = rankB → sameTypeCompare = 0 → indexA < indexB → res = -1
  ensures rankA = rankB → sameTypeCompare = 0 → indexA > indexB → res = 1
  ensures rankA = rankB → sameTypeCompare = 0 → indexA = indexB → res = 0
  do
    return Pure.compareGroupKey rankA rankB sameTypeCompare indexA indexB

method isNumericType (typeChar : String) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ typeChar = "n"
  do
    return Pure.isNumericType typeChar

method isBlankType (typeChar : String) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ typeChar = "b"
  do
    return Pure.isBlankType typeChar

method aggregateContributesNumeric (typeChar : String) return (res : Bool)
  ensures res = Pure.isNumericType typeChar
  do
    return Pure.aggregateContributesNumeric typeChar

method aggregateContributesCountA (typeChar : String) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ Pure.isBlankType typeChar = false
  do
    return Pure.aggregateContributesCountA typeChar

method aggregateContributes (aggFn : Int) (typeChar : String) return (res : Bool)
  ensures aggFn = 2 → res = Pure.aggregateContributesCountA typeChar
  ensures aggFn ≠ 2 → res = Pure.aggregateContributesNumeric typeChar
  do
    return Pure.aggregateContributes aggFn typeChar

method nextSum (sum : Int) (contributes : Bool) (value : Int) return (res : Int)
  ensures contributes = true → res = sum + value
  ensures contributes = false → res = sum
  do
    return Pure.nextSum sum contributes value

method nextCount (count : Int) (contributes : Bool) return (res : Int)
  ensures contributes = true → res = count + 1
  ensures contributes = false → res = count
  do
    return Pure.nextCount count contributes

method nextMin (min : Int) (hasMin : Bool) (contributes : Bool) (value : Int) return (res : Int)
  ensures contributes = false → res = min
  ensures contributes = true → hasMin = false → res = value
  ensures contributes = true → hasMin = true → value < min → res = value
  ensures contributes = true → hasMin = true → value ≥ min → res = min
  do
    return Pure.nextMin min hasMin contributes value

method nextMax (max : Int) (hasMax : Bool) (contributes : Bool) (value : Int) return (res : Int)
  ensures contributes = false → res = max
  ensures contributes = true → hasMax = false → res = value
  ensures contributes = true → hasMax = true → value > max → res = value
  ensures contributes = true → hasMax = true → value ≤ max → res = max
  do
    return Pure.nextMax max hasMax contributes value

method aggregateStatus (aggFn : Int) (numericCount : Int) return (res : Int)
  ensures aggFn = 3 → numericCount = 0 → res = 1
  ensures aggFn ≠ 3 ∨ numericCount ≠ 0 → res = 0
  do
    return Pure.aggregateStatus aggFn numericCount

method isValidPivotShape (rows : Int) (cols : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ rows > 0 ∧ cols > 0
  do
    return Pure.isValidPivotShape rows cols

method pivotEndCol (anchorCol : Int) (cols : Int) return (res : Int)
  ensures res = anchorCol + cols - 1
  do
    return Pure.pivotEndCol anchorCol cols

method pivotEndRow (anchorRow : Int) (rows : Int) return (res : Int)
  ensures res = anchorRow + rows - 1
  do
    return Pure.pivotEndRow anchorRow rows

method isPivotWithinBounds (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) (maxCol : Int) (maxRow : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ anchorCol ≥ 1 ∧ anchorRow ≥ 1 ∧ Pure.pivotEndCol anchorCol cols ≤ maxCol ∧ Pure.pivotEndRow anchorRow rows ≤ maxRow
  do
    return Pure.isPivotWithinBounds anchorCol anchorRow rows cols maxCol maxRow

method pivotCellCount (rows : Int) (cols : Int) return (res : Int)
  ensures res = rows * cols
  do
    return Pure.pivotCellCount rows cols

method isPivotWithinBudget (rows : Int) (cols : Int) (maxCells : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ Pure.pivotCellCount rows cols ≤ maxCells
  do
    return Pure.isPivotWithinBudget rows cols maxCells

method planPivotStatus (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) (maxCol : Int) (maxRow : Int) (maxCells : Int) return (res : Int)
  ensures Pure.isValidPivotShape rows cols = false → res = 1
  ensures Pure.isValidPivotShape rows cols = true → Pure.isPivotWithinBounds anchorCol anchorRow rows cols maxCol maxRow = false → res = 2
  ensures Pure.isValidPivotShape rows cols = true → Pure.isPivotWithinBounds anchorCol anchorRow rows cols maxCol maxRow = true → Pure.isPivotWithinBudget rows cols maxCells = false → res = 3
  ensures res = 0 ↔ Pure.isValidPivotShape rows cols = true ∧ Pure.isPivotWithinBounds anchorCol anchorRow rows cols maxCol maxRow = true ∧ Pure.isPivotWithinBudget rows cols maxCells = true
  ensures res = 0 → rows > 0 ∧ cols > 0
  ensures res = 0 → anchorCol ≥ 1 ∧ anchorRow ≥ 1
  ensures res = 0 → Pure.pivotEndCol anchorCol cols ≤ maxCol ∧ Pure.pivotEndRow anchorRow rows ≤ maxRow
  do
    return Pure.planPivotStatus anchorCol anchorRow rows cols maxCol maxRow maxCells

method classifyPivotClaim (isAnchorCell : Bool) (isBlank : Bool) (isOwnedBySamePivot : Bool) (isForeignOwned : Bool) (hasUserContent : Bool) (isMergedTarget : Bool) return (res : Int)
  ensures res = 0 ∨ res = 1 ∨ res = 2
  ensures isAnchorCell = true → res = 0
  ensures isAnchorCell = false → isBlank = true ∨ isOwnedBySamePivot = true → isForeignOwned = false → hasUserContent = false → isMergedTarget = false → res = 1
  ensures isAnchorCell = false → isForeignOwned = true → res = 2
  ensures isAnchorCell = false → hasUserContent = true → res = 2
  ensures isAnchorCell = false → isMergedTarget = true → res = 2
  ensures isAnchorCell = false → isForeignOwned = true → res ≠ 0 ∧ res ≠ 1
  ensures isAnchorCell = false → hasUserContent = true → res ≠ 0 ∧ res ≠ 1
  ensures isAnchorCell = false → isMergedTarget = true → res ≠ 0 ∧ res ≠ 1
  do
    return Pure.classifyPivotClaim isAnchorCell isBlank isOwnedBySamePivot isForeignOwned hasUserContent isMergedTarget
