/-
  Generated by lsc from protect.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «protect.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isSheetProtected (protectedAttrib : Bool) return (res : Bool)
  do
    return Pure.isSheetProtected protectedAttrib

method isCellEditable (sheetProtected : Bool) (cellReadonly : Bool) (cellUnlocked : Bool) return (res : Bool)
  do
    return Pure.isCellEditable sheetProtected cellReadonly cellUnlocked
