/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def isSheetProtected (protectedAttrib : Bool) : Bool :=
  protectedAttrib

def isCellEditable (sheetProtected : Bool) (cellReadonly : Bool) (cellUnlocked : Bool) : Bool :=
  if cellReadonly then
    false
  else
    if ¬(sheetProtected) then
      true
    else
      cellUnlocked

end Pure
