/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def isValidShape (rows : Int) (cols : Int) : Bool :=
  rows > 0 ∧ cols > 0

def endCol (anchorCol : Int) (cols : Int) : Int :=
  anchorCol + cols - 1

def endRow (anchorRow : Int) (rows : Int) : Int :=
  anchorRow + rows - 1

def isWithinBounds (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) (maxCol : Int) (maxRow : Int) : Bool :=
  anchorCol ≥ 1 ∧ anchorRow ≥ 1 ∧ endCol anchorCol cols ≤ maxCol ∧ endRow anchorRow rows ≤ maxRow

def spillCellCount (rows : Int) (cols : Int) : Int :=
  rows * cols

def isWithinBudget (rows : Int) (cols : Int) (maxCells : Int) : Bool :=
  spillCellCount rows cols ≤ maxCells

def planSpillStatus (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) (maxCol : Int) (maxRow : Int) (maxCells : Int) : Int :=
  if ¬(isValidShape rows cols) then
    1
  else
    if ¬(isWithinBounds anchorCol anchorRow rows cols maxCol maxRow) then
      2
    else
      if ¬(isWithinBudget rows cols maxCells) then
        3
      else
        0

def classifySpillClaim (isAnchorCell : Bool) (isBlank : Bool) (isOwnedBySameAnchor : Bool) (isForeignSpill : Bool) (hasUserContent : Bool) (isMergedTarget : Bool) : Int :=
  if isAnchorCell = true then
    0
  else
    if isForeignSpill = true ∨ hasUserContent = true ∨ isMergedTarget = true then
      2
    else
      if isBlank = true ∨ isOwnedBySameAnchor = true then
        1
      else
        2

def inSpillRect (col : Int) (row : Int) (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) : Bool :=
  col ≥ anchorCol ∧ col ≤ endCol anchorCol cols ∧ row ≥ anchorRow ∧ row ≤ endRow anchorRow rows

def classifyResizeMembership (inOld : Bool) (inNew : Bool) : Int :=
  if inOld ∧ inNew then
    0
  else
    if ¬(inOld) ∧ inNew then
      1
    else
      if inOld ∧ ¬(inNew) then
        2
      else
        3

def resizeAction (membership : Int) : Int :=
  if membership = 2 then
    1
  else
    if membership = 1 then
      2
    else
      0

def isFirstOccurrenceAt (index : Int) (firstIndexOfValue : Int) : Bool :=
  index = firstIndexOfValue

def occursExactlyOnce (count : Int) : Bool :=
  count = 1

def keepUniqueRow (index : Int) (firstIndexOfValue : Int) (count : Int) (exactlyOnce : Bool) : Bool :=
  if exactlyOnce = true then
    occursExactlyOnce count
  else
    isFirstOccurrenceAt index firstIndexOfValue

def stableCompare (comparatorResult : Int) (indexA : Int) (indexB : Int) : Int :=
  if comparatorResult ≠ 0 then
    comparatorResult
  else
    if indexA < indexB then
      -1
    else
      if indexA > indexB then
        1
      else
        0

end Pure
