/-
  Generated by lsc from spill.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «spill.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isValidShape (rows : Int) (cols : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ rows > 0 ∧ cols > 0
  do
    return Pure.isValidShape rows cols

method endCol (anchorCol : Int) (cols : Int) return (res : Int)
  ensures res = anchorCol + cols - 1
  do
    return Pure.endCol anchorCol cols

method endRow (anchorRow : Int) (rows : Int) return (res : Int)
  ensures res = anchorRow + rows - 1
  do
    return Pure.endRow anchorRow rows

method isWithinBounds (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) (maxCol : Int) (maxRow : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ anchorCol ≥ 1 ∧ anchorRow ≥ 1 ∧ Pure.endCol anchorCol cols ≤ maxCol ∧ Pure.endRow anchorRow rows ≤ maxRow
  do
    return Pure.isWithinBounds anchorCol anchorRow rows cols maxCol maxRow

method spillCellCount (rows : Int) (cols : Int) return (res : Int)
  ensures res = rows * cols
  do
    return Pure.spillCellCount rows cols

method isWithinBudget (rows : Int) (cols : Int) (maxCells : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ Pure.spillCellCount rows cols ≤ maxCells
  do
    return Pure.isWithinBudget rows cols maxCells

method planSpillStatus (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) (maxCol : Int) (maxRow : Int) (maxCells : Int) return (res : Int)
  ensures Pure.isValidShape rows cols = false → res = 1
  ensures Pure.isValidShape rows cols = true → Pure.isWithinBounds anchorCol anchorRow rows cols maxCol maxRow = false → res = 2
  ensures Pure.isValidShape rows cols = true → Pure.isWithinBounds anchorCol anchorRow rows cols maxCol maxRow = true → Pure.isWithinBudget rows cols maxCells = false → res = 3
  ensures res = 0 ↔ Pure.isValidShape rows cols = true ∧ Pure.isWithinBounds anchorCol anchorRow rows cols maxCol maxRow = true ∧ Pure.isWithinBudget rows cols maxCells = true
  ensures res = 0 → rows > 0 ∧ cols > 0
  ensures res = 0 → anchorCol ≥ 1 ∧ anchorRow ≥ 1
  ensures res = 0 → Pure.endCol anchorCol cols ≤ maxCol ∧ Pure.endRow anchorRow rows ≤ maxRow
  ensures res = 0 → Pure.spillCellCount rows cols > 0
  ensures res = 0 → Pure.spillCellCount rows cols = rows * cols
  do
    return Pure.planSpillStatus anchorCol anchorRow rows cols maxCol maxRow maxCells

method classifySpillClaim (isAnchorCell : Bool) (isBlank : Bool) (isOwnedBySameAnchor : Bool) (isForeignSpill : Bool) (hasUserContent : Bool) (isMergedTarget : Bool) return (res : Int)
  ensures res = 0 ∨ res = 1 ∨ res = 2
  ensures isAnchorCell = true → res = 0
  ensures isAnchorCell = false → isBlank = true ∨ isOwnedBySameAnchor = true → isForeignSpill = false → hasUserContent = false → isMergedTarget = false → res = 1
  ensures isAnchorCell = false → isForeignSpill = true → res = 2
  ensures isAnchorCell = false → hasUserContent = true → res = 2
  ensures isAnchorCell = false → isMergedTarget = true → res = 2
  ensures isAnchorCell = false → isForeignSpill = true → res ≠ 0 ∧ res ≠ 1
  ensures isAnchorCell = false → hasUserContent = true → res ≠ 0 ∧ res ≠ 1
  ensures isAnchorCell = false → isMergedTarget = true → res ≠ 0 ∧ res ≠ 1
  do
    return Pure.classifySpillClaim isAnchorCell isBlank isOwnedBySameAnchor isForeignSpill hasUserContent isMergedTarget

method inSpillRect (col : Int) (row : Int) (anchorCol : Int) (anchorRow : Int) (rows : Int) (cols : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ col ≥ anchorCol ∧ col ≤ Pure.endCol anchorCol cols ∧ row ≥ anchorRow ∧ row ≤ Pure.endRow anchorRow rows
  do
    return Pure.inSpillRect col row anchorCol anchorRow rows cols

method classifyResizeMembership (inOld : Bool) (inNew : Bool) return (res : Int)
  ensures res = 0 ∨ res = 1 ∨ res = 2 ∨ res = 3
  ensures inOld = true → inNew = true → res = 0
  ensures inOld = false → inNew = true → res = 1
  ensures inOld = true → inNew = false → res = 2
  ensures inOld = false → inNew = false → res = 3
  do
    return Pure.classifyResizeMembership inOld inNew

method resizeAction (membership : Int) return (res : Int)
  ensures membership = 2 → res = 1
  ensures membership = 1 → res = 2
  ensures membership = 0 → res = 0
  ensures membership = 3 → res = 0
  do
    return Pure.resizeAction membership

method isFirstOccurrenceAt (index : Int) (firstIndexOfValue : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ index = firstIndexOfValue
  do
    return Pure.isFirstOccurrenceAt index firstIndexOfValue

method occursExactlyOnce (count : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ count = 1
  do
    return Pure.occursExactlyOnce count

method keepUniqueRow (index : Int) (firstIndexOfValue : Int) (count : Int) (exactlyOnce : Bool) return (res : Bool)
  ensures res = true ∨ res = false
  ensures exactlyOnce = false → res = Pure.isFirstOccurrenceAt index firstIndexOfValue
  ensures exactlyOnce = true → res = Pure.occursExactlyOnce count
  ensures exactlyOnce = false → index ≠ firstIndexOfValue → res = false
  ensures exactlyOnce = true → count ≠ 1 → res = false
  do
    return Pure.keepUniqueRow index firstIndexOfValue count exactlyOnce

method stableCompare (comparatorResult : Int) (indexA : Int) (indexB : Int) return (res : Int)
  ensures comparatorResult ≠ 0 → res = comparatorResult
  ensures comparatorResult = 0 → indexA < indexB → res = -1
  ensures comparatorResult = 0 → indexA > indexB → res = 1
  ensures comparatorResult = 0 → indexA = indexB → res = 0
  do
    return Pure.stableCompare comparatorResult indexA indexB
