/-
  Generated by lsc from statistics.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «statistics.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method doubledAverageRank (bestRank : Int) (tieCount : Int) return (res : Int)
  ensures res = 2 * bestRank + tieCount - 1
  ensures tieCount = 1 → res = 2 * bestRank
  do
    return Pure.doubledAverageRank bestRank tieCount

method quartileExcScaledPosition (n : Int) (quart : Int) return (res : Int)
  ensures res = quart * (n + 1)
  do
    return Pure.quartileExcScaledPosition n quart

method isValidQuartileExcPosition (n : Int) (quart : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ Pure.quartileExcScaledPosition n quart ≥ 4 ∧ Pure.quartileExcScaledPosition n quart ≤ 4 * n
  do
    return Pure.isValidQuartileExcPosition n quart
