/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def doubledAverageRank (bestRank : Int) (tieCount : Int) : Int :=
  2 * bestRank + tieCount - 1

def quartileExcScaledPosition (n : Int) (quart : Int) : Int :=
  quart * (n + 1)

def isValidQuartileExcPosition (n : Int) (quart : Int) : Bool :=
  let scaled := quartileExcScaledPosition n quart
  scaled ≥ 4 ∧ scaled ≤ 4 * n

end Pure
