// Generated by lsc from validation.ts

function isBlank(raw: string): bool
{
  (raw == "")
}

lemma isBlank_ensures(raw: string)
  ensures ((isBlank(raw) == true) || (isBlank(raw) == false))
  ensures ((isBlank(raw) == true) <==> (raw == ""))
{
}

function compareOk(op: string, value: int, bound1: int, bound2: int): bool
{
  if (op == "between") then
    ((value >= bound1) && (value <= bound2))
  else
    if (op == "notBetween") then
      ((value < bound1) || (value > bound2))
    else
      if (op == "eq") then
        (value == bound1)
      else
        if (op == "ne") then
          (value != bound1)
        else
          if (op == "gt") then
            (value > bound1)
          else
            if (op == "lt") then
              (value < bound1)
            else
              if (op == "ge") then
                (value >= bound1)
              else
                ((op == "le") && (value <= bound1))
}

lemma compareOk_ensures(op: string, value: int, bound1: int, bound2: int)
  ensures ((compareOk(op, value, bound1, bound2) == true) || (compareOk(op, value, bound1, bound2) == false))
  ensures ((op == "between") ==> ((compareOk(op, value, bound1, bound2) == true) <==> ((value >= bound1) && (value <= bound2))))
  ensures ((op == "notBetween") ==> ((compareOk(op, value, bound1, bound2) == true) <==> ((value < bound1) || (value > bound2))))
  ensures ((op == "eq") ==> ((compareOk(op, value, bound1, bound2) == true) <==> (value == bound1)))
  ensures ((op == "ne") ==> ((compareOk(op, value, bound1, bound2) == true) <==> (value != bound1)))
  ensures ((op == "gt") ==> ((compareOk(op, value, bound1, bound2) == true) <==> (value > bound1)))
  ensures ((op == "lt") ==> ((compareOk(op, value, bound1, bound2) == true) <==> (value < bound1)))
  ensures ((op == "ge") ==> ((compareOk(op, value, bound1, bound2) == true) <==> (value >= bound1)))
  ensures ((op == "le") ==> ((compareOk(op, value, bound1, bound2) == true) <==> (value <= bound1)))
  ensures ((op != "between") ==> (op != "notBetween") ==> (op != "eq") ==> (op != "ne") ==> (op != "gt") ==> (op != "lt") ==> (op != "ge") ==> (op != "le") ==> (compareOk(op, value, bound1, bound2) == false))
{
}

function computeOutcome(allowBlank: bool, isBlankValue: bool, checkPassed: bool, mode: string): string
{
  if ((allowBlank == true) && (isBlankValue == true)) then
    "pass"
  else
    if (checkPassed == true) then
      "pass"
    else
      if (mode == "warn") then
        "warn"
      else
        "reject"
}

lemma computeOutcome_ensures(allowBlank: bool, isBlankValue: bool, checkPassed: bool, mode: string)
  ensures (((computeOutcome(allowBlank, isBlankValue, checkPassed, mode) == "pass") || (computeOutcome(allowBlank, isBlankValue, checkPassed, mode) == "warn")) || (computeOutcome(allowBlank, isBlankValue, checkPassed, mode) == "reject"))
  ensures ((allowBlank == true) ==> (isBlankValue == true) ==> (computeOutcome(allowBlank, isBlankValue, checkPassed, mode) == "pass"))
  ensures (((allowBlank == false) || (isBlankValue == false)) ==> (checkPassed == true) ==> (computeOutcome(allowBlank, isBlankValue, checkPassed, mode) == "pass"))
  ensures (((allowBlank == false) || (isBlankValue == false)) ==> (checkPassed == false) ==> (mode == "warn") ==> (computeOutcome(allowBlank, isBlankValue, checkPassed, mode) == "warn"))
  ensures (((allowBlank == false) || (isBlankValue == false)) ==> (checkPassed == false) ==> (mode != "warn") ==> (computeOutcome(allowBlank, isBlankValue, checkPassed, mode) == "reject"))
{
}
