/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def isBlank (raw : String) : Bool :=
  raw = ""

def compareOk (op : String) (value : Int) (bound1 : Int) (bound2 : Int) : Bool :=
  if op = "between" then
    value ≥ bound1 ∧ value ≤ bound2
  else
    if op = "notBetween" then
      value < bound1 ∨ value > bound2
    else
      if op = "eq" then
        value = bound1
      else
        if op = "ne" then
          value ≠ bound1
        else
          if op = "gt" then
            value > bound1
          else
            if op = "lt" then
              value < bound1
            else
              if op = "ge" then
                value ≥ bound1
              else
                if op = "le" then
                  value ≤ bound1
                else
                  false

def computeOutcome (allowBlank : Bool) (isBlankValue : Bool) (checkPassed : Bool) (mode : String) : String :=
  if allowBlank = true ∧ isBlankValue = true then
    "pass"
  else
    if checkPassed = true then
      "pass"
    else
      if mode = "warn" then
        "warn"
      else
        "reject"

end Pure
