/-
  Generated by lsc from validation.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «validation.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isBlank (raw : String) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ raw = ""
  do
    return Pure.isBlank raw

method compareOk (op : String) (value : Int) (bound1 : Int) (bound2 : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures op = "between" → (res = true ↔ value ≥ bound1 ∧ value ≤ bound2)
  ensures op = "notBetween" → (res = true ↔ value < bound1 ∨ value > bound2)
  ensures op = "eq" → (res = true ↔ value = bound1)
  ensures op = "ne" → (res = true ↔ value ≠ bound1)
  ensures op = "gt" → (res = true ↔ value > bound1)
  ensures op = "lt" → (res = true ↔ value < bound1)
  ensures op = "ge" → (res = true ↔ value ≥ bound1)
  ensures op = "le" → (res = true ↔ value ≤ bound1)
  ensures op ≠ "between" → op ≠ "notBetween" → op ≠ "eq" → op ≠ "ne" → op ≠ "gt" → op ≠ "lt" → op ≠ "ge" → op ≠ "le" → res = false
  do
    return Pure.compareOk op value bound1 bound2

method computeOutcome (allowBlank : Bool) (isBlankValue : Bool) (checkPassed : Bool) (mode : String) return (res : String)
  ensures res = "pass" ∨ res = "warn" ∨ res = "reject"
  ensures allowBlank = true → isBlankValue = true → res = "pass"
  ensures allowBlank = false ∨ isBlankValue = false → checkPassed = true → res = "pass"
  ensures allowBlank = false ∨ isBlankValue = false → checkPassed = false → mode = "warn" → res = "warn"
  ensures allowBlank = false ∨ isBlankValue = false → checkPassed = false → mode ≠ "warn" → res = "reject"
  do
    return Pure.computeOutcome allowBlank isBlankValue checkPassed mode
