/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def isEffectivelyHidden (manualHidden : Bool) (filterHidden : Bool) : Bool :=
  manualHidden = true ∨ filterHidden = true

def manualHiddenAfterFilterClear (manualHiddenBefore : Bool) : Bool :=
  manualHiddenBefore

def filterHiddenAfterManualClear (filterHiddenBefore : Bool) : Bool :=
  filterHiddenBefore

def recomputeFilterHidden (failsAnyCriterion : Bool) : Bool :=
  failsAnyCriterion

def recomputeIsIdempotent (failsAnyCriterion : Bool) : Bool :=
  recomputeFilterHidden failsAnyCriterion = recomputeFilterHidden failsAnyCriterion

def isInFilterDataBand (row : Int) (headerRow : Int) (lastRow : Int) : Bool :=
  row > headerRow ∧ row ≤ lastRow

def outOfBandNeverFilterHidden (inBand : Bool) (failsAnyCriterion : Bool) : Bool :=
  inBand = true ∧ failsAnyCriterion = true

end Pure
