/-
  Generated by lsc from visibility.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «visibility.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isEffectivelyHidden (manualHidden : Bool) (filterHidden : Bool) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ manualHidden = true ∨ filterHidden = true
  do
    return Pure.isEffectivelyHidden manualHidden filterHidden

method manualHiddenAfterFilterClear (manualHiddenBefore : Bool) return (res : Bool)
  ensures res = manualHiddenBefore
  do
    return Pure.manualHiddenAfterFilterClear manualHiddenBefore

method filterHiddenAfterManualClear (filterHiddenBefore : Bool) return (res : Bool)
  ensures res = filterHiddenBefore
  do
    return Pure.filterHiddenAfterManualClear filterHiddenBefore

method recomputeFilterHidden (failsAnyCriterion : Bool) return (res : Bool)
  ensures res = failsAnyCriterion
  do
    return Pure.recomputeFilterHidden failsAnyCriterion

method recomputeIsIdempotent (failsAnyCriterion : Bool) return (res : Bool)
  ensures res = true
  do
    return Pure.recomputeIsIdempotent failsAnyCriterion

method isInFilterDataBand (row : Int) (headerRow : Int) (lastRow : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ row > headerRow ∧ row ≤ lastRow
  do
    return Pure.isInFilterDataBand row headerRow lastRow

method outOfBandNeverFilterHidden (inBand : Bool) (failsAnyCriterion : Bool) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ inBand = true ∧ failsAnyCriterion = true
  do
    return Pure.outOfBandNeverFilterHidden inBand failsAnyCriterion
