/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def pow2 (n : Int) : Int :=
  if n = 0 then
    1
  else
    if n = 1 then
      2
    else
      if n = 2 then
        4
      else
        if n = 3 then
          8
        else
          if n = 4 then
            16
          else
            if n = 5 then
              32
            else
              64

def isLegalWeekendCode (code : Int) : Bool :=
  code ≥ 1 ∧ code ≤ 7 ∨ code ≥ 11 ∧ code ≤ 17

def weekendPairFirstDay (code : Int) : Int :=
  Int.tmod (code + 4) 7

def weekendSingleDay (code : Int) : Int :=
  Int.tmod (code + 2) 7

def weekendCodeToMask (code : Int) : Int :=
  if code ≥ 1 ∧ code ≤ 7 then
    let first := weekendPairFirstDay code
    let second := Int.tmod (first + 1) 7
    pow2 first + pow2 second
  else
    if code ≥ 11 ∧ code ≤ 17 then
      pow2 (weekendSingleDay code)
    else
      127

def isLegalWeekendMask (mask : Int) : Bool :=
  mask ≥ 0 ∧ mask ≤ 127 ∧ mask ≠ 127

def isLegalMaskChar (charCode : Int) : Bool :=
  charCode = 48 ∨ charCode = 49

def maskDayOff (mask : Int) (isoDow : Int) : Bool :=
  Int.tmod (mask / pow2 isoDow) 2 = 1

def sundayDowToIsoDow (sundayDow : Int) : Int :=
  Int.tmod (sundayDow + 6) 7

def isNonWorkingDay (mask : Int) (isoDow : Int) (isHoliday : Bool) : Bool :=
  maskDayOff mask isoDow = true ∨ isHoliday = true

def isWorkingDay (mask : Int) (isoDow : Int) (isHoliday : Bool) : Bool :=
  isNonWorkingDay mask isoDow isHoliday = false

def stepDirection (count : Int) : Int :=
  if count > 0 then
    1
  else
    if count < 0 then
      -1
    else
      0

end Pure
