/-
  Generated by lsc from weekday-policy.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «weekday-policy.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method pow2 (n : Int) return (res : Int)
  require n ≥ 0
  require n ≤ 6
  ensures n = 0 → res = 1
  ensures n = 1 → res = 2
  ensures n = 2 → res = 4
  ensures n = 3 → res = 8
  ensures n = 4 → res = 16
  ensures n = 5 → res = 32
  ensures n = 6 → res = 64
  do
    return Pure.pow2 n

method isLegalWeekendCode (code : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ code ≥ 1 ∧ code ≤ 7 ∨ code ≥ 11 ∧ code ≤ 17
  do
    return Pure.isLegalWeekendCode code

method weekendPairFirstDay (code : Int) return (res : Int)
  require code ≥ 1
  require code ≤ 7
  ensures res ≥ 0
  ensures res ≤ 6
  ensures res = Int.tmod (code + 4) 7
  do
    return Pure.weekendPairFirstDay code

method weekendSingleDay (code : Int) return (res : Int)
  require code ≥ 11
  require code ≤ 17
  ensures res ≥ 0
  ensures res ≤ 6
  ensures res = Int.tmod (code + 2) 7
  do
    return Pure.weekendSingleDay code

method weekendCodeToMask (code : Int) return (res : Int)
  ensures Pure.isLegalWeekendCode code = false → res = 127
  ensures code ≥ 1 → code ≤ 7 → res = Pure.pow2 (Pure.weekendPairFirstDay code) + Pure.pow2 (Int.tmod (Pure.weekendPairFirstDay code + 1) 7)
  ensures code ≥ 11 → code ≤ 17 → res = Pure.pow2 (Pure.weekendSingleDay code)
  do
    return Pure.weekendCodeToMask code

method isLegalWeekendMask (mask : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ mask ≥ 0 ∧ mask ≤ 127 ∧ mask ≠ 127
  do
    return Pure.isLegalWeekendMask mask

method isLegalMaskChar (charCode : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ charCode = 48 ∨ charCode = 49
  do
    return Pure.isLegalMaskChar charCode

method maskDayOff (mask : Int) (isoDow : Int) return (res : Bool)
  require isoDow ≥ 0
  require isoDow ≤ 6
  ensures res = true ∨ res = false
  do
    return Pure.maskDayOff mask isoDow

method sundayDowToIsoDow (sundayDow : Int) return (res : Int)
  require sundayDow ≥ 0
  require sundayDow ≤ 6
  ensures res ≥ 0
  ensures res ≤ 6
  ensures res = Int.tmod (sundayDow + 6) 7
  do
    return Pure.sundayDowToIsoDow sundayDow

method isNonWorkingDay (mask : Int) (isoDow : Int) (isHoliday : Bool) return (res : Bool)
  require isoDow ≥ 0
  require isoDow ≤ 6
  ensures res = true ∨ res = false
  ensures res = true ↔ Pure.maskDayOff mask isoDow = true ∨ isHoliday = true
  do
    return Pure.isNonWorkingDay mask isoDow isHoliday

method isWorkingDay (mask : Int) (isoDow : Int) (isHoliday : Bool) return (res : Bool)
  require isoDow ≥ 0
  require isoDow ≤ 6
  ensures res = true ∨ res = false
  ensures res = true ↔ Pure.isNonWorkingDay mask isoDow isHoliday = false
  do
    return Pure.isWorkingDay mask isoDow isHoliday

method stepDirection (count : Int) return (res : Int)
  ensures res = -1 ∨ res = 0 ∨ res = 1
  ensures count > 0 → res = 1
  ensures count < 0 → res = -1
  ensures count = 0 → res = 0
  do
    return Pure.stepDirection count
