/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def validateSheetName (isEmpty : Bool) (exceedsMaxLength : Bool) (hasInvalidChar : Bool) (isDuplicate : Bool) : Int :=
  if isEmpty then
    NAME_EMPTY
  else
    if exceedsMaxLength then
      NAME_TOO_LONG
    else
      if hasInvalidChar then
        NAME_INVALID_CHARS
      else
        if isDuplicate then
          NAME_DUPLICATE
        else
          NAME_OK

def isNameAccepted (code : Int) : Bool :=
  code = NAME_OK

def canHideAnotherSheet (visibleCount : Int) : Bool :=
  visibleCount > MIN_VISIBLE_SHEETS

def canDeleteAnotherSheet (totalCount : Int) : Bool :=
  totalCount > 1

def clampIndex (index : Int) (count : Int) : Int :=
  if count ≤ 0 then
    NO_INDEX
  else
    if index < 0 then
      0
    else
      if index ≥ count then
        count - 1
      else
        index

def activeIndexAfterDelete (deletedIndex : Int) (activeIndex : Int) (oldCount : Int) : Int :=
  if oldCount ≤ 1 then
    NO_INDEX
  else
    let newCount := oldCount - 1
    if deletedIndex < activeIndex then
      clampIndex (activeIndex - 1) newCount
    else
      clampIndex activeIndex newCount

def activeIndexAfterHide (nextVisibleIndex : Int) (prevVisibleIndex : Int) : Int :=
  if nextVisibleIndex ≥ 0 then
    nextVisibleIndex
  else
    if prevVisibleIndex ≥ 0 then
      prevVisibleIndex
    else
      NO_INDEX

def reorderTargetIndex (requestedIndex : Int) (count : Int) : Int :=
  if count ≤ 0 then
    NO_INDEX
  else
    clampIndex requestedIndex count

def classifyReferenceRewrite (referencesAffectedSheet : Bool) (isDelete : Bool) : Int :=
  if ¬(referencesAffectedSheet) then
    REF_UNCHANGED
  else
    if isDelete then
      REF_BROKEN
    else
      REF_RENAMED

end Pure
