/-
  Generated by lsc from workbook.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «workbook.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

def NAME_OK : Int := 0

def NAME_EMPTY : Int := 1

def NAME_TOO_LONG : Int := 2

def NAME_INVALID_CHARS : Int := 3

def NAME_DUPLICATE : Int := 4

def MIN_VISIBLE_SHEETS : Int := 1

def NO_INDEX : Int := -1

def REF_UNCHANGED : Int := 0

def REF_RENAMED : Int := 1

def REF_BROKEN : Int := 2

method validateSheetName (isEmpty : Bool) (exceedsMaxLength : Bool) (hasInvalidChar : Bool) (isDuplicate : Bool) return (res : Int)
  ensures isEmpty = true → res = 1
  ensures isEmpty = false → exceedsMaxLength = true → res = 2
  ensures isEmpty = false → exceedsMaxLength = false → hasInvalidChar = true → res = 3
  ensures isEmpty = false → exceedsMaxLength = false → hasInvalidChar = false → isDuplicate = true → res = 4
  ensures res = 0 ↔ isEmpty = false ∧ exceedsMaxLength = false ∧ hasInvalidChar = false ∧ isDuplicate = false
  do
    return Pure.validateSheetName isEmpty exceedsMaxLength hasInvalidChar isDuplicate

method isNameAccepted (code : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ code = 0
  do
    return Pure.isNameAccepted code

method canHideAnotherSheet (visibleCount : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ visibleCount > 1
  do
    return Pure.canHideAnotherSheet visibleCount

method canDeleteAnotherSheet (totalCount : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ totalCount > 1
  do
    return Pure.canDeleteAnotherSheet totalCount

method clampIndex (index : Int) (count : Int) return (res : Int)
  ensures count ≤ 0 → res = -1
  ensures count > 0 → index < 0 → res = 0
  ensures count > 0 → index ≥ count → res = count - 1
  ensures count > 0 → index ≥ 0 → index < count → res = index
  do
    return Pure.clampIndex index count

method activeIndexAfterDelete (deletedIndex : Int) (activeIndex : Int) (oldCount : Int) return (res : Int)
  ensures oldCount ≤ 1 → res = -1
  ensures oldCount > 1 → deletedIndex < activeIndex → res = Pure.clampIndex (activeIndex - 1) (oldCount - 1)
  ensures oldCount > 1 → deletedIndex > activeIndex → res = Pure.clampIndex activeIndex (oldCount - 1)
  ensures oldCount > 1 → deletedIndex = activeIndex → res = Pure.clampIndex activeIndex (oldCount - 1)
  do
    return Pure.activeIndexAfterDelete deletedIndex activeIndex oldCount

method activeIndexAfterHide (nextVisibleIndex : Int) (prevVisibleIndex : Int) return (res : Int)
  ensures nextVisibleIndex ≥ 0 → res = nextVisibleIndex
  ensures nextVisibleIndex = -1 → prevVisibleIndex ≥ 0 → res = prevVisibleIndex
  ensures nextVisibleIndex = -1 → prevVisibleIndex = -1 → res = -1
  do
    return Pure.activeIndexAfterHide nextVisibleIndex prevVisibleIndex

method reorderTargetIndex (requestedIndex : Int) (count : Int) return (res : Int)
  ensures count ≤ 0 → res = -1
  ensures count > 0 → res = Pure.clampIndex requestedIndex count
  do
    return Pure.reorderTargetIndex requestedIndex count

method classifyReferenceRewrite (referencesAffectedSheet : Bool) (isDelete : Bool) return (res : Int)
  ensures referencesAffectedSheet = false → res = 0
  ensures referencesAffectedSheet = true → isDelete = true → res = 2
  ensures referencesAffectedSheet = true → isDelete = false → res = 1
  do
    return Pure.classifyReferenceRewrite referencesAffectedSheet isDelete
