/-
  Generated by lsc from xlookup.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «xlookup.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

def MATCH_NEXT_SMALLER : Int := -1

def MATCH_NEXT_LARGER : Int := 1

def MATCH_WILDCARD : Int := 2

def SEARCH_BINARY_ASC : Int := 2

def SEARCH_BINARY_DESC : Int := -2

def OUTCOME_MISS : Int := 0

def OUTCOME_EXACT : Int := 1

def OUTCOME_APPROXIMATE : Int := 2

def FALLBACK_NOT_FOUND_ERROR : String := "#N/A"

method matchModeValidity (matchMode : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ matchMode = -1 ∨ matchMode = 0 ∨ matchMode = 1 ∨ matchMode = 2
  do
    return Pure.matchModeValidity matchMode

method searchModeValidity (searchMode : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ searchMode = 1 ∨ searchMode = -1 ∨ searchMode = 2 ∨ searchMode = -2
  do
    return Pure.searchModeValidity searchMode

method modeCombinationValidity (matchMode : Int) (searchMode : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true → Pure.matchModeValidity matchMode = true
  ensures res = true → Pure.searchModeValidity searchMode = true
  ensures Pure.matchModeValidity matchMode = false → res = false
  ensures Pure.searchModeValidity searchMode = false → res = false
  ensures matchMode = MATCH_WILDCARD → searchMode = SEARCH_BINARY_ASC ∨ searchMode = SEARCH_BINARY_DESC → res = false
  ensures Pure.matchModeValidity matchMode = true → Pure.searchModeValidity searchMode = true → ¬(matchMode = MATCH_WILDCARD ∧ (searchMode = SEARCH_BINARY_ASC ∨ searchMode = SEARCH_BINARY_DESC)) → res = true
  do
    return Pure.modeCombinationValidity matchMode searchMode

method matchOutcomeToResult (foundExact : Bool) (foundApproximate : Bool) return (res : Int)
  ensures res = OUTCOME_MISS ∨ res = OUTCOME_EXACT ∨ res = OUTCOME_APPROXIMATE
  ensures foundExact = true → res = OUTCOME_EXACT
  ensures foundExact = false → foundApproximate = true → res = OUTCOME_APPROXIMATE
  ensures foundExact = false → foundApproximate = false → res = OUTCOME_MISS
  do
    return Pure.matchOutcomeToResult foundExact foundApproximate

method matchModeAllowsApproximate (matchMode : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ matchMode = MATCH_NEXT_SMALLER ∨ matchMode = MATCH_NEXT_LARGER
  do
    return Pure.matchModeAllowsApproximate matchMode

method classifyLookupOutcome (matchMode : Int) (foundExact : Bool) (foundApproximate : Bool) return (res : Int)
  ensures res = OUTCOME_MISS ∨ res = OUTCOME_EXACT ∨ res = OUTCOME_APPROXIMATE
  ensures foundExact = true → res = OUTCOME_EXACT
  ensures foundExact = false → foundApproximate = true → Pure.matchModeAllowsApproximate matchMode = true → res = OUTCOME_APPROXIMATE
  ensures foundExact = false → Pure.matchModeAllowsApproximate matchMode = false → res = OUTCOME_MISS
  ensures foundExact = false → foundApproximate = false → res = OUTCOME_MISS
  do
    return Pure.classifyLookupOutcome matchMode foundExact foundApproximate

method resolveIfNotFound (outcome : Int) (hasIfNotFound : Bool) (ifNotFoundValue : String) return (res : String)
  ensures outcome ≠ OUTCOME_MISS → res = ""
  ensures outcome = OUTCOME_MISS → hasIfNotFound = true → res = ifNotFoundValue
  ensures outcome = OUTCOME_MISS → hasIfNotFound = false → res = FALLBACK_NOT_FOUND_ERROR
  do
    return Pure.resolveIfNotFound outcome hasIfNotFound ifNotFoundValue
