/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def matchModeValidity (matchMode : Int) : Bool :=
  matchMode = -1 ∨ matchMode = 0 ∨ matchMode = 1 ∨ matchMode = 2

def searchModeValidity (searchMode : Int) : Bool :=
  searchMode = 1 ∨ searchMode = -1 ∨ searchMode = 2 ∨ searchMode = -2

def modeCombinationValidity (matchMode : Int) (searchMode : Int) : Bool :=
  if matchModeValidity matchMode = false then
    false
  else
    if searchModeValidity searchMode = false then
      false
    else
      if matchMode = MATCH_WILDCARD ∧ (searchMode = SEARCH_BINARY_ASC ∨ searchMode = SEARCH_BINARY_DESC) then
        false
      else
        true

def matchOutcomeToResult (foundExact : Bool) (foundApproximate : Bool) : Int :=
  if foundExact = true then
    OUTCOME_EXACT
  else
    if foundApproximate = true then
      OUTCOME_APPROXIMATE
    else
      OUTCOME_MISS

def matchModeAllowsApproximate (matchMode : Int) : Bool :=
  matchMode = MATCH_NEXT_SMALLER ∨ matchMode = MATCH_NEXT_LARGER

def classifyLookupOutcome (matchMode : Int) (foundExact : Bool) (foundApproximate : Bool) : Int :=
  if foundExact = true then
    OUTCOME_EXACT
  else
    if foundApproximate = true ∧ matchModeAllowsApproximate matchMode = true then
      OUTCOME_APPROXIMATE
    else
      OUTCOME_MISS

def resolveIfNotFound (outcome : Int) (hasIfNotFound : Bool) (ifNotFoundValue : String) : String :=
  if outcome ≠ OUTCOME_MISS then
    ""
  else
    if hasIfNotFound = true then
      ifNotFoundValue
    else
      FALLBACK_NOT_FOUND_ERROR

end Pure
